version: '3.8'

services:

  api:
    image: projeto2-api:latest
    build:
      context: ./Gateway
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  consumer:
    image: projeto2-consumer:latest
    build:
      context: ./consumer-python
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.11-management
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: overlay
